spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234
mybatis:
  mapper-locations: classpath:mapper/*.xml
